export interface Post {
  slug: string
  title: string
  excerpt?: string
  date?: string
  readTime?: string
  featured?: boolean
  category: string
}

export const posts: Post[] = [
  // Featured post
  {
    slug: "why-termote",
    title: "Why I Built Termote: An SSH Alternative",
    excerpt: "After years of dealing with SSH configuration, port forwarding, and VPN setup, I decided there had to be a better way to access my terminal from anywhere.",
    date: "2024-03-15",
    readTime: "5 min read",
    featured: true,
    category: "ai-coding-agents",
  },
  // AI Coding Agents category
  {
    slug: "ai-coding-agents/run-claude-code-from-anywhere",
    title: "Run Claude Code From Anywhere (Full Setup Guide)",
    excerpt: "A complete guide to running Claude Code remotely using Termote, so you can code from any device with a browser.",
    date: "2024-03-14",
    readTime: "8 min read",
    category: "ai-coding-agents",
  },
  {
    slug: "ai-coding-agents/use-ai-coding-agents-from-phone",
    title: "How to Use AI Coding Agents From Your Phone",
    excerpt: "Turn your phone into a mobile coding station. Here's how to control Claude Code, Codex CLI, and other AI agents from a mobile browser.",
    date: "2024-03-13",
    readTime: "6 min read",
    category: "ai-coding-agents",
  },
  {
    slug: "ai-coding-agents/best-setup-running-ai-agents-24-7",
    title: "Best Setup for Running AI Coding Agents 24/7",
    excerpt: "Leave AI agents running overnight? Here's the hardware and software setup that keeps them productive around the clock.",
    date: "2024-03-12",
    readTime: "7 min read",
    category: "ai-coding-agents",
  },
  {
    slug: "ai-coding-agents/claude-code-vs-codex-cli",
    title: "Claude Code vs Codex CLI: Which Should You Use?",
    excerpt: "Comparing the two most powerful terminal-based AI coding agents. Here's when to use each one.",
    date: "2024-03-11",
    readTime: "5 min read",
    category: "ai-coding-agents",
  },
  {
    slug: "ai-coding-agents/control-ai-coding-agent-from-anywhere",
    title: "Control Your AI Coding Agent From Anywhere",
    excerpt: "Don't be chained to your desk. Learn how to monitor and control your AI coding agent from any location.",
    date: "2024-03-10",
    readTime: "4 min read",
    category: "ai-coding-agents",
  },
  {
    slug: "ai-coding-agents/run-ai-coding-agents-while-outside",
    title: "How I Run AI Coding Agents While I'm Outside",
    excerpt: "My daily workflow: start a task at home, check progress from the coffee shop, review results at dinner.",
    date: "2024-03-09",
    readTime: "5 min read",
    category: "ai-coding-agents",
  },
  {
    slug: "ai-coding-agents/ultimate-remote-dev-setup-ai-terminal-browser",
    title: "The Ultimate Remote Dev Setup (AI + Terminal + Browser)",
    excerpt: "The complete setup that gives you a full development environment accessible from any device with a browser.",
    date: "2024-03-08",
    readTime: "10 min read",
    category: "ai-coding-agents",
  },
  {
    slug: "ai-coding-agents/run-codex-cli-on-home-pc-anywhere",
    title: "Run Codex CLI on Your Home PC and Access It Anywhere",
    excerpt: "Use your home computer's GPU for Codex CLI tasks while traveling. Here's the complete setup guide.",
    date: "2024-03-07",
    readTime: "6 min read",
    category: "ai-coding-agents",
  },
  {
    slug: "ai-coding-agents/why-ai-coding-tools-need-remote-access",
    title: "Why AI Coding Tools Need Remote Access",
    excerpt: "AI coding agents are most powerful when they run on your fastest machine. Remote access makes that possible.",
    date: "2024-03-06",
    readTime: "4 min read",
    category: "ai-coding-agents",
  },
  {
    slug: "ai-coding-agents/build-while-you-sleep-ai-agents-overnight",
    title: "Build While You Sleep: Running AI Agents Overnight",
    excerpt: "Start a codebase refactor at 11pm, wake up to a completed project. Here's how to run AI agents for long overnight tasks.",
    date: "2024-03-05",
    readTime: "7 min read",
    category: "ai-coding-agents",
  },
  {
    slug: "ai-coding-agents/monitor-ai-code-generation-real-time",
    title: "How to Monitor AI Code Generation in Real-Time",
    excerpt: "Watch your AI agent work without staring at a terminal. Methods for monitoring AI coding progress from anywhere.",
    date: "2024-03-04",
    readTime: "5 min read",
    category: "ai-coding-agents",
  },
  {
    slug: "ai-coding-agents/turn-phone-into-dev-console",
    title: "Turn Your Phone Into a Dev Console",
    excerpt: "Use your phone as a mobile terminal to check builds, run AI agents, and manage your dev workflow.",
    date: "2024-03-03",
    readTime: "4 min read",
    category: "ai-coding-agents",
  },
  {
    slug: "ai-coding-agents/best-tools-ai-powered-development-2026",
    title: "Best Tools for AI-Powered Development (2026)",
    excerpt: "The complete landscape of AI coding tools in 2026, from terminal-based agents to browser-based IDEs.",
    date: "2024-03-02",
    readTime: "8 min read",
    category: "ai-coding-agents",
  },
  {
    slug: "ai-coding-agents/local-ai-coding-agents-beat-cloud-ides",
    title: "Why Local AI Coding Agents Beat Cloud IDEs",
    excerpt: "Your data stays local, your models run faster, and you don't depend on subscription cloud services.",
    date: "2024-03-01",
    readTime: "6 min read",
    category: "ai-coding-agents",
  },
  {
    slug: "ai-coding-agents/run-entire-dev-environment-in-browser",
    title: "Run Your Entire Dev Environment in a Browser (Without the Cloud)",
    excerpt: "Browser-based terminal + local dev environment = full-stack development from a chromebook.",
    date: "2024-02-28",
    readTime: "5 min read",
    category: "ai-coding-agents",
  },
  {
    slug: "ai-coding-agents/multi-agent-coding-workflows",
    title: "Multi-Agent Coding Workflows (And How to Manage Them)",
    excerpt: "Running multiple AI coding agents in parallel? Here's how to coordinate them effectively.",
    date: "2024-02-27",
    readTime: "7 min read",
    category: "ai-coding-agents",
  },
  {
    slug: "ai-coding-agents/debug-code-remotely-using-ai-agents",
    title: "How to Debug Code Remotely Using AI Agents",
    excerpt: "Fix bugs on a production server without SSH. Use a browser-based terminal with AI debugging assistance.",
    date: "2024-02-26",
    readTime: "5 min read",
    category: "ai-coding-agents",
  },
  {
    slug: "ai-coding-agents/future-of-coding-ai-agents-remote-terminals",
    title: "The Future of Coding: AI Agents + Remote Terminals",
    excerpt: "Where this is heading: AI agents running on your home lab, controlled from any device, anywhere in the world.",
    date: "2024-02-25",
    readTime: "4 min read",
    category: "ai-coding-agents",
  },
  {
    slug: "ai-coding-agents/run-terminal-based-ai-tools-any-device",
    title: "Run Terminal-Based AI Tools on Any Device",
    excerpt: "Terminal-based AI tools like Claude Code and Codex CLI aren't just for desktop. Here's how to use them anywhere.",
    date: "2024-02-24",
    readTime: "5 min read",
    category: "ai-coding-agents",
  },
  {
    slug: "ai-coding-agents/from-terminal-to-anywhere-new-dev-workflow",
    title: "From Terminal to Anywhere: The New Dev Workflow",
    excerpt: "The terminal-first development workflow, reimagined for the mobile-first world. Code from anywhere.",
    date: "2024-02-23",
    readTime: "6 min read",
    category: "ai-coding-agents",
  },
  // Remote Access category
  {
    slug: "remote-access/access-computer-remotely-without-ssh-vpn",
    title: "How to Access Your Computer Remotely Without SSH or VPN",
    excerpt: "No port forwarding, no VPN setup, no firewall config. Just open a browser and connect to your PC.",
    date: "2024-02-22",
    readTime: "5 min read",
    category: "remote-access",
  },
  {
    slug: "remote-access/port-22-blocked-ways-to-access-server",
    title: "Port 22 Blocked? 7 Ways to Access Your Server Anyway",
    excerpt: "Corporate firewall blocking SSH? Here are seven working alternatives to get remote terminal access.",
    date: "2024-02-21",
    readTime: "7 min read",
    category: "remote-access",
  },
  {
    slug: "remote-access/best-ssh-alternatives-2026",
    title: "Best SSH Alternatives in 2026 (Tested & Compared)",
    excerpt: "Web-based terminals, browser tunnels, and reverse connections. We tested the top SSH alternatives.",
    date: "2024-02-20",
    readTime: "8 min read",
    category: "remote-access",
  },
  {
    slug: "remote-access/access-pc-from-phone-no-apps",
    title: "How to Access Your PC From Your Phone (No Apps Required)",
    excerpt: "Need to check a build from your phone? Here's how to access your computer through a browser with no installation.",
    date: "2024-02-19",
    readTime: "4 min read",
    category: "remote-access",
  },
  {
    slug: "remote-access/why-ssh-fails-corporate-networks",
    title: "Why SSH Fails on Corporate Networks (And How to Fix It)",
    excerpt: "Port 22 is blocked, proxies reject your connection, VPN is too slow. Here's the modern solution.",
    date: "2024-02-18",
    readTime: "5 min read",
    category: "remote-access",
  },
  {
    slug: "remote-access/remote-terminal-access-without-port-forwarding",
    title: "Remote Terminal Access Without Port Forwarding (Beginner Guide)",
    excerpt: "The simplest explanation of why port forwarding is unnecessary with modern web-based terminals.",
    date: "2024-02-17",
    readTime: "6 min read",
    category: "remote-access",
  },
  {
    slug: "remote-access/use-browser-as-full-terminal",
    title: "How to Use Your Browser as a Full Terminal (Step-by-Step)",
    excerpt: "Your browser can be a full-featured terminal. Here's how to set it up in under 5 minutes.",
    date: "2024-02-16",
    readTime: "5 min read",
    category: "remote-access",
  },
  {
    slug: "remote-access/tmux-vs-modern-web-terminals",
    title: "tmux vs Modern Web Terminals: Do You Still Need tmux?",
    excerpt: "Modern web terminals have built-in multi-pane support. Is tmux still necessary for remote workflows?",
    date: "2024-02-15",
    readTime: "5 min read",
    category: "remote-access",
  },
  {
    slug: "remote-access/access-localhost-from-anywhere-without-ngrok",
    title: "Access Your Localhost From Anywhere (Without Ngrok)",
    excerpt: "Ngrok is great but costs money. Here's a free alternative for accessing your localhost from anywhere.",
    date: "2024-02-14",
    readTime: "4 min read",
    category: "remote-access",
  },
  {
    slug: "remote-access/best-remote-development-tools-2026",
    title: "Best Remote Development Tools for Developers (2026)",
    excerpt: "A comprehensive review of the top remote development tools, from web terminals to cloud workspaces.",
    date: "2024-02-13",
    readTime: "9 min read",
    category: "remote-access",
  },
  {
    slug: "remote-access/bypass-firewalls-legally-development-work",
    title: "How to Bypass Firewalls Legally for Development Work",
    excerpt: "Network restrictions blocking your dev work? These are legitimate techniques that don't violate policy.",
    date: "2024-02-12",
    readTime: "6 min read",
    category: "remote-access",
  },
  {
    slug: "remote-access/ssh-vs-https-tunnels-reliability",
    title: "SSH vs HTTPS Tunnels: What's More Reliable?",
    excerpt: "HTTPS tunnels work through proxies and firewalls that SSH can't penetrate. Here's the reliability comparison.",
    date: "2024-02-11",
    readTime: "5 min read",
    category: "remote-access",
  },
  {
    slug: "remote-access/run-terminal-commands-on-pc-from-anywhere",
    title: "Run Terminal Commands on Your PC From Anywhere",
    excerpt: "Start a build, check logs, restart a service. Run any terminal command from your phone or tablet.",
    date: "2024-02-10",
    readTime: "3 min read",
    category: "remote-access",
  },
  {
    slug: "remote-access/monitor-long-running-jobs-remotely",
    title: "How to Monitor Long-Running Jobs Remotely",
    excerpt: "Keep an eye on builds, training jobs, and server processes from anywhere with a browser.",
    date: "2024-02-09",
    readTime: "5 min read",
    category: "remote-access",
  },
  {
    slug: "remote-access/no-vpn-no-ssh-simplest-remote-access",
    title: "No VPN, No SSH: The Simplest Remote Access Setup Ever",
    excerpt: "One-click remote access without configuring anything. This is the future of terminal access.",
    date: "2024-02-08",
    readTime: "4 min read",
    category: "remote-access",
  },
  {
    slug: "remote-access/why-mobile-ssh-clients-are-terrible",
    title: "Why Mobile SSH Clients Are Terrible (And What to Use Instead)",
    excerpt: "Touch键盘 + SSH = frustration. Browser-based terminals solve all the problems with mobile SSH.",
    date: "2024-02-07",
    readTime: "5 min read",
    category: "remote-access",
  },
  {
    slug: "remote-access/secure-remote-access-without-opening-ports",
    title: "How to Secure Remote Access Without Opening Ports",
    excerpt: "Reverse tunnels and browser-based connections don't require open ports. Here's how to stay secure.",
    date: "2024-02-06",
    readTime: "6 min read",
    category: "remote-access",
  },
  {
    slug: "remote-access/access-home-server-from-anywhere-behind-nat",
    title: "Access Your Home Server From Anywhere (Even Behind NAT)",
    excerpt: "Home networks with NAT make remote access tricky. Modern tunnels solve this without port forwarding.",
    date: "2024-02-05",
    readTime: "5 min read",
    category: "remote-access",
  },
  {
    slug: "remote-access/best-tools-control-pc-from-anywhere",
    title: "Best Tools to Control Your PC From Anywhere",
    excerpt: "Comparing the top tools for remote PC control, from full desktops to terminal-only access.",
    date: "2024-02-04",
    readTime: "7 min read",
    category: "remote-access",
  },
  {
    slug: "remote-access/fixed-server-from-restaurant-using-phone",
    title: "How I Fixed My Server From a Restaurant Using My Phone",
    excerpt: "A real story: 45 minutes to fix a broken server, all from a coffee shop using my phone browser.",
    date: "2024-02-03",
    readTime: "4 min read",
    category: "remote-access",
  },
  // Terminal Productivity category
  {
    slug: "terminal-productivity/manage-multiple-terminals-without-losing-mind",
    title: "How to Manage Multiple Terminals Without Losing Your Mind",
    excerpt: "The mental overhead of 10 terminal tabs vs one organized workspace. Here's how to stay sane.",
    date: "2024-02-02",
    readTime: "5 min read",
    category: "terminal-productivity",
  },
  {
    slug: "terminal-productivity/frontend-backend-ai-agents-one-terminal-workspace",
    title: "Frontend, Backend, and AI Agents — All in One Terminal Workspace",
    excerpt: "Run your frontend build, backend server, and AI coding agent side by side in one organized view.",
    date: "2024-02-01",
    readTime: "6 min read",
    category: "terminal-productivity",
  },
  {
    slug: "terminal-productivity/stop-using-10-terminal-tabs",
    title: "Stop Using 10 Terminal Tabs — Do This Instead",
    excerpt: "Tabs are for web browsers, not terminals. Multi-pane layouts are the proper way to organize terminals.",
    date: "2024-01-31",
    readTime: "4 min read",
    category: "terminal-productivity",
  },
  {
    slug: "terminal-productivity/best-way-organize-terminal-full-stack-development",
    title: "Best Way to Organize Your Terminal for Full-Stack Development",
    excerpt: "One pane for frontend, one for backend, one for database, one for AI agents. Here's the layout.",
    date: "2024-01-30",
    readTime: "6 min read",
    category: "terminal-productivity",
  },
  {
    slug: "terminal-productivity/tmux-is-powerful-but-also-mess",
    title: "tmux Is Powerful — But It's Also a Mess",
    excerpt: "tmux has a steep learning curve and cryptic shortcuts. Modern terminal multiplexers are easier.",
    date: "2024-01-29",
    readTime: "5 min read",
    category: "terminal-productivity",
  },
  {
    slug: "terminal-productivity/better-way-handle-multiple-terminals-no-tmux",
    title: "A Better Way to Handle Multiple Terminals (No tmux Needed)",
    excerpt: "Built-in multi-pane support means you don't need tmux. Here's why GUI-based terminal multiplexers win.",
    date: "2024-01-28",
    readTime: "5 min read",
    category: "terminal-productivity",
  },
  {
    slug: "terminal-productivity/run-monitor-multiple-processes-at-once",
    title: "How to Run and Monitor Multiple Processes at Once",
    excerpt: "Keep all your dev servers and build processes visible in one screen. No more switching between windows.",
    date: "2024-01-27",
    readTime: "4 min read",
    category: "terminal-productivity",
  },
  {
    slug: "terminal-productivity/cleanest-terminal-setup-developers-2026",
    title: "The Cleanest Terminal Setup for Developers in 2026",
    excerpt: "The minimal, distraction-free terminal setup that top developers are using this year.",
    date: "2024-01-26",
    readTime: "7 min read",
    category: "terminal-productivity",
  },
  {
    slug: "terminal-productivity/why-terminal-workflow-feels-chaotic",
    title: "Why Your Terminal Workflow Feels Chaotic (And How to Fix It)",
    excerpt: "The problem isn't the terminal — it's the organization. Multi-pane layouts bring order to chaos.",
    date: "2024-01-25",
    readTime: "5 min read",
    category: "terminal-productivity",
  },
  {
    slug: "terminal-productivity/group-rename-search-missing-terminal-features",
    title: "Group, Rename, Search: The Missing Features in Most Terminals",
    excerpt: "What terminals are missing: named groups, search across panes, and organized workspaces.",
    date: "2024-01-24",
    readTime: "5 min read",
    category: "terminal-productivity",
  },
  {
    slug: "terminal-productivity/track-logs-servers-builds-one-screen",
    title: "How to Track Logs, Servers, and Builds in One Screen",
    excerpt: "See all your running processes, logs, and builds in a single organized dashboard view.",
    date: "2024-01-23",
    readTime: "4 min read",
    category: "terminal-productivity",
  },
  {
    slug: "terminal-productivity/run-frontend-backend-database-one-view",
    title: "Run Frontend, Backend, and Database in One View",
    excerpt: "Split your terminal into three panes: frontend, backend, and database. Never switch contexts again.",
    date: "2024-01-22",
    readTime: "5 min read",
    category: "terminal-productivity",
  },
  {
    slug: "terminal-productivity/problem-with-terminal-tabs-panes-better",
    title: "The Problem With Terminal Tabs (And Why Panes Are Better)",
    excerpt: "Tabs hide context. Panes reveal it. Here's why you should switch from tabs to panes.",
    date: "2024-01-21",
    readTime: "4 min read",
    category: "terminal-productivity",
  },
  {
    slug: "terminal-productivity/stay-organized-running-ai-coding-agents",
    title: "How to Stay Organized While Running AI Coding Agents",
    excerpt: "Running Claude Code or Codex CLI alongside your other work? Here's how to keep everything organized.",
    date: "2024-01-20",
    readTime: "5 min read",
    category: "terminal-productivity",
  },
  {
    slug: "terminal-productivity/control-multiple-ai-agents-one-dashboard",
    title: "Control Multiple AI Agents From One Dashboard",
    excerpt: "Run multiple AI coding agents in separate panes. Monitor all of them from one screen.",
    date: "2024-01-19",
    readTime: "6 min read",
    category: "terminal-productivity",
  },
  {
    slug: "terminal-productivity/terminal-is-mess-heres-how-fix-it",
    title: "Your Terminal Is a Mess — Here's How to Fix It",
    excerpt: "Too many windows, too many tabs, too much context switching. Here's the organized alternative.",
    date: "2024-01-18",
    readTime: "5 min read",
    category: "terminal-productivity",
  },
  {
    slug: "terminal-productivity/build-unified-dev-workspace-without-heavy-ide",
    title: "How to Build a Unified Dev Workspace (Without a Heavy IDE)",
    excerpt: "Skip VS Code. Use a terminal multiplexer + editor + browser. Here's the lightweight alternative.",
    date: "2024-01-17",
    readTime: "7 min read",
    category: "terminal-productivity",
  },
  {
    slug: "terminal-productivity/minimalist-developer-setup-everything-one-terminal-ui",
    title: "Minimalist Developer Setup: Everything in One Terminal UI",
    excerpt: "The complete minimalist dev setup: one terminal window, multiple panes, everything in view.",
    date: "2024-01-16",
    readTime: "5 min read",
    category: "terminal-productivity",
  },
  {
    slug: "terminal-productivity/switch-less-build-more-context-switching",
    title: "Switch Less, Build More: Fixing Context Switching in Dev Workflows",
    excerpt: "Every window switch costs context. Multi-pane layouts keep your brain in the flow state.",
    date: "2024-01-15",
    readTime: "5 min read",
    category: "terminal-productivity",
  },
  {
    slug: "terminal-productivity/from-8-terminal-windows-to-one-clean-dashboard",
    title: "From 8 Terminal Windows to One Clean Dashboard",
    excerpt: "How I consolidated 8 terminal windows into one organized dashboard — and never looked back.",
    date: "2024-01-14",
    readTime: "6 min read",
    category: "terminal-productivity",
  },
]

export const categories = [
  {
    slug: "ai-coding-agents",
    title: "AI Coding Agents",
    description: "Learn how to use and control AI coding agents remotely from any device.",
    href: "/blog/ai-coding-agents",
  },
  {
    slug: "remote-access",
    title: "Remote Access",
    description: "Guides for accessing your terminal without SSH, VPN, or port forwarding.",
    href: "/blog/remote-access",
  },
  {
    slug: "terminal-productivity",
    title: "Terminal Productivity",
    description: "Organize your workflow with multi-pane layouts, groups, and clean dashboards.",
    href: "/blog/terminal-productivity",
  },
]

export function getFeaturedPost(): Post | undefined {
  return posts.find((post) => post.featured)
}

export function getPostsByCategory(category: string): Post[] {
  return posts.filter((post) => post.category === category)
}

export function getAllPosts(): Post[] {
  return posts
}

export function getNonFeaturedPosts(): Post[] {
  return posts.filter((post) => !post.featured)
}
